version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "9000:9000"
    networks:
      - appnet

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "9090:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
