apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hemanthkumar21/my-flask-frontend:latest
          ports:
            - containerPort: 80  # Exposing port 80 for Nginx
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9090        # Exposing port 9090 on the service
      targetPort: 80    # Targeting port 80 on the container where Nginx is listening
  type: LoadBalancer
